apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grade-kustomize
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arjnbli9/gitops.git
    targetRevision: HEAD
    path: apps/grade-submission-api-helm
    helm:
      valuesFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: grade-kustomize
  syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
